language: objective-c

install:
 - brew update > /dev/null
 - brew --config
 - brew --env
 # install swig 2.0.11
 # look at all versions
 - brew versions swig
 # 2.0.11   git checkout b51b660 Library/Formula/swig.rb
 - (cd $(brew --prefix); git checkout b51b660 Library/Formula/swig.rb)
 - brew install swig
 # restore brew's versions
 - (cd $(brew --prefix); git checkout HEAD Library/Formula/swig.rb)
 # install go with all cross compiles
 - brew unlink go
 - brew install go --cross-compile-all
 # install libtorrent-rasterbar 0.16.13
 - brew versions libtorrent-rasterbar
 - (cd $(brew --prefix); git checkout 08eda3b Library/Formula/libtorrent-rasterbar.rb)
 - brew install libtorrent-rasterbar
 - (cd $(brew --prefix); git checkout HEAD Library/Formula/libtorrent-rasterbar.rb)

script:
 - mkdir -p gopath/src/github.com/steeve
 - git clone https://github.com/steeve/libtorrent-go.git gopath/src/github.com/steeve/libtorrent-go
 - export GOPATH=$PWD/gopath
 - make
